# Generated by Django 3.2.7 on 2021-11-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20211117_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='area',
            new_name='area_hectares',
        ),
    ]
